services:

  # nginx - run docker compose up
  web:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
      build:
          dockerfile: ./php/Dockerfile
      volumes:
        - /var/www/html/vendor
        - ./app:/var/www/html
  db:
      image: mysql:latest
      volumes:
        - mysqldata:/var/lib/mysql
      ports:
        - "4306:3306"
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_USER: user
        MYSQL_PASSWORD: toor
        MYSQL_DATABASE: docker-php


volumes:
  mysqldata:
